services:
  mongodb:
    image: mongo:7
    container_name: gym-db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: gym-api
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      SECRET_KEY: ${SECRET_KEY}
      BREVO_USER: ${BREVO_USER}
      BREVO_SMTP_KEY: ${BREVO_SMTP_KEY}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks:
      - app-network
    command: npm run dev

volumes:
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge
